### ISSUE TITLE
update install instructions

### ISSUE THREAD

**Issue by Trass3r** [GrammaTech/ddisasm#18]
There seem to be packages for `focal` but the readme is outdated.
A docker container with preinstalled ddisasm could also be useful.

```sh
$ docker run --rm -it ubuntu
apt update && apt install -y ca-certificates 
echo "deb [trusted=yes] https://grammatech.github.io/gtirb/pkgs/focal ./" > /etc/apt/sources.list.d/gtirb.list
apt update && apt install -y ddisasm
```

**Comment by jeshan** [comment]
> A docker container with preinstalled ddisasm

I've just pushed this:
https://hub.docker.com/r/jeshan/ddisasm

Let me know how it goes.
I will later see if we can get this merged to this repository.

**Comment by eschulte** [comment]
We're working on our CI process to automatically maintain our public packages (and to do a better job of versioning) for ddisasm, gtirb, and gtirb-pprinter.  Once that is complete we're going to update the [GTIRB manual](https://grammatech.github.io/gtirb/) and the relevant READMEs.  We'll circle back here once this is complete.

**Comment by eschulte** [comment]
GTIRB's CI is now automatically generating and uploading Ubuntu packages to track both versioned releases and the development HEAD.  See [https://grammatech.github.io/gtirb/#installing](https://grammatech.github.io/gtirb/#installing) for more information.
