### ISSUE TITLE
exim fails disassembly

### ISSUE THREAD

**Issue by jrmuizel** [GrammaTech/ddisasm#22]
exim compiled with icc-19.1.1.219 fails with:

```
ddisasm ./exim --asm exim.s
Building the initial gtirb representation  (118ms)
Decoding the binary  (20s)
Disassembling (92s)
Populating gtirb representation  (11s)
Computing intra-procedural SCCs  (1s)
Computing no return analysis  (5s)
Detecting additional functions  (3s)
Printing assembler WARNING: found overlapping element at address 4fd492
The --layout option to gtirb-pprinter can fix overlapping elements.
 (es)
The conflicts between the following code blocks could not be resolved:
4fd490 - 4fd492
Aborting
```

This is with ddisasm 1.4 (1cbb62c)

I've attached the binary
[exim.zip](https://github.com/GrammaTech/ddisasm/files/6086359/exim.zip)

I ran into this while trying out ddisasm on https://github.com/pangine/disasm-benchmark

**Comment by junghee** [comment]
I tried running it with the latest master (daa0ab84960925d64fcf6c5c2ddb4462a392e50f), and found it worked fine. It is highly likely that it got fixed at some point last couple months.
