### ISSUE TITLE
Broken link to "Control Flow Integrity for COTS Binaries" paper

### ISSUE THREAD

**Issue by mewmew** [GrammaTech/ddisasm#3]
The link to http://www.stonecat.com/repos/reading/papers/12313-sec13-paper_zhang.pdf results in a 404 error page.

**Comment by mewmew** [comment]
Similarly, the [link](http://delivery.acm.org/10.1145/2940000/2931047/p24-meng.pdf?ip=98.159.213.242&id=2931047&acc=CHORUS&key=4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E6D218144511F3437&__acm__=1539001930_dedfe0a1aa0c9bf006dbe0874ff74722) to the "Binary Code is Not Easy" paper results the the following error message:

```
An error occurred while processing your request.
Reference #50.5c27db17.1557766749.37b105cc
```

**Comment by aeflores** [comment]
Thanks! they should be working now
