### ISSUE TITLE
Too many build errors

### ISSUE THREAD

**Issue by expnkx** [GrammaTech/ddisasm#30]
/usr/local/include/souffle/utility/ParallelUtil.h:110:7: error: use of deleted function 'std::mutex::mutex(const std::mutex&)'
In file included from /usr/local/include/c++/12.0.0/mutex:43,
                 from /usr/local/include/souffle/SignalHandler.h:25,
                 from /usr/local/include/souffle/CompiledSouffle.h:21,
                 from /home/cqwrteur/ddisasm/src/gtirb-decoder/DatalogProgram.h:26,
                 from /home/cqwrteur/ddisasm/src/gtirb-decoder/DatalogProgram.cpp:23:
/usr/local/include/c++/12.0.0/bits/std_mutex.h:94:5: note: declared here
   94 |     mutex(const mutex&) = delete;
      |     ^~~~~
/home/cqwrteur/ddisasm/src/gtirb-decoder/DatalogProgram.cpp:66:41: error: 'class souffle::SymbolTable' has no member named 'resolve'
   66 |                     File << SymbolTable.resolve(Tuple[I]);
      |                                         ^~~~~~~

After I did some changes, it crashes at build.

cqwrteur@BU-Precision-Tower-5810:~/ddisasm_build$ ninja
[1/23] Generating souffle_function_inference.cpp
FAILED: src/passes/souffle_function_inference.cpp 
cd /home/cqwrteur/ddisasm_build/src/passes && /usr/local/bin/souffle /home/cqwrteur/ddisasm/src/passes/datalog/function_inference.dl -g souffle_function_inference.cpp -jauto
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to locate mcpp pre-processor
Aborted (core dumped)
[2/23] Generating souffle_no_return.cpp
FAILED: src/passes/souffle_no_return.cpp 
cd /home/cqwrteur/ddisasm_build/src/passes && /usr/local/bin/souffle /home/cqwrteur/ddisasm/src/passes/datalog/no_return_analysis.dl -g souffle_no_return.cpp -jauto
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to locate mcpp pre-processor
Aborted (core dumped)

**Comment by kwarrick** [comment]
Hi @expnkx, it appears you are missing a build dependency:

> what(): failed to locate mcpp pre-processor

```
sudo apt install mcpp
```

**Comment by eschulte** [comment]
Closing this for now, please reopen if the above doesn't fix the problem.
