### ISSUE TITLE
Question: How to perform "reduce" on the binary

### ISSUE THREAD

**Issue by swang206** [GrammaTech/ddisasm#32]
I just saw in an introduction of gtirb and ddisasm that they can perform "reduce" that remove some features in the binary, or debloat binary. How to use "reduce" and "debloating" with ddisasm???

**Comment by swang206** [comment]
https://eschulte.github.io/data/debloat-datasheet.pdf

**Comment by kwarrick** [comment]
Hi @swang206,

Binary transforms (i.e. "reduce")  aren't part of ddisasm proper. They are implemented independently with the GTIRB API.

You might consider it a pipeline:

```
binary -> [ ddisasm ] -> gtirb -> [ transform ] -> gtirb' -> [ gtirb-pprinter ] -> assembly ...
```

You can write `[ transform ]`s to arbitrarily manipulate the GTIRB file in the API of your choice (i.e. Python, C++, CL), but there is also a higher-level "rewriting" API: [gtirb-rewriting](https://github.com/GrammaTech/gtirb-rewriting).

These examples might interested you as well:

- https://github.com/GrammaTech/gtirb-search-reduce
- https://github.com/GrammaTech/gtirb/blob/master/doc/examples/stack-stamp.md
