### ISSUE TITLE
Any support for AT&T？

### ISSUE THREAD

**Issue by YOURLEGEND** [GrammaTech/ddisasm#45]
The assembly file generated by ddisasm are in Intel. Is there any options to generate AT&T assembly files which can be (re)assembled back by GCC?

**Comment by eschulte** [comment]
Yes ddisasm supports AT&T syntax output.  DDisasm actually uses `gtirb-pprinter` to print assembly.  You can first generate a GTIRB file and then generate an AT&T assembly file as follows.
```
ddisasm /bin/ls --ir /tmp/ls.gtirb
gtirb-pprinter /tmp/ls.gtirb -s att -a /tmp/ls.s
```
