### ISSUE TITLE
[non-pie] fails to disassemble on ubuntu-20.04.6 : process killed

### ISSUE THREAD

**Issue by gogo2464** [GrammaTech/ddisasm#60]
ddisasm --version
1.6.0 (cfa30e80 2023-03-21) ARM64+IA32+X64+ARM32+MIPS32

The process is killed. I do not see the asm output yet.

$ ddisasm non-pie --asm PacketTracer.asm
Building the initial gtirb representation [    2s]
Processing module: PacketTracer
    disassembly              load Killed

**Comment by aeflores** [comment]
Hi @gogo2464 
Thanks for opening and issue and showing interest in Ddisasm!

We will investigate this case, but my first guess is that the process is running out of RAM. The binary that you pointed out is ~90MB. 

Ddisasm is pretty memory intensive. As a rough estimation, any binary over ~20MB is likely going to require more than 32GB of RAM. We are working on lowering the memory consumption to be able to handle bigger, but that will likely take some time.

**Comment by gogo2464** [comment]
No problem. I am just setting my computer to use 500GB of swap. If you want I can document on the repo what I did.

Could we just set an option to see percent of adavance on each step?

Thank you very much for your answer.

**Comment by aeflores** [comment]
> I am just setting my computer to use 500GB of swap

I am curious, did it work?

> Could we just set an option to see percent of adavance on each step?

Most of the disassembly work is done by the Datalog code (which is transformed to C++ by [souffle](https://github.com/souffle-lang/souffle)) so it is not straightforward to record progress there.

**Comment by gogo2464** [comment]
"I am curious, did it work?"

Yes :) after 3 days of processing. :) I set up my computer in order to avoid to shutdown automatically.




We might store intermediate calculus into sqlite? What do you think of this idea?

**Comment by gogo2464** [comment]
@aeflores I can not recompile it.

ddisasm disassemble with these logs:


Building the initial gtirb representation [    2s]

Processing module: PacketTracer

    disassembly              load [38m44s]    compute 



[ 39h3m]  transform WARNING: Moving symbol to first block of section: __bss_start

[33m19s]

    SCC analysis                              compute [ 2m19s]  transform [   0ms]

    no return analysis       load [ 4m29s]    compute [44m24s]  transform [ 702ms]

    function inference       load [ 7m41s]    compute [ 5m40s]  transform [  1m1s]

Printing assembler [20m24s]



then I did:




I got no error to run it but a segfault and valgrind

**Comment by gogo2464** [comment]
@aeflores do I open an issue?

**Comment by aeflores** [comment]
Hi @gogo2464  I there is no need to open another issue. Can you clarify, did you manage to reassemble but the rewritten binary crashes? or did the reassembly itself crashed?

Do you have a way of sharing Ddisasm's gtirb file or the assembly output with us?

**Comment by gogo2464** [comment]
Yes the binary crashes once recompiled. Can I send you the assembly by email please? I am currently on my phone.  I need to wait before sending you the assembly.

**Comment by gogo2464** [comment]
@aeflores I sent you an email. Did you received it?

**Comment by aeflores** [comment]
I did! Unfortunately, it might take me some time to get to it.

**Comment by gogo2464** [comment]
@aeflores Ah alright. No problem. Sorry. I will wait.

**Comment by gogo2464** [comment]
@aeflores should I ask my question on another canal please?

**Comment by aeflores** [comment]
As of https://github.com/GrammaTech/ddisasm/commit/2fd73fea0c9641d82528623711f120e2893907de this issue should be solved.
